import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../app/globals.css";
import NavBar from "@/src/components/NavBar";
import Footer from "@/src/components/Footer";
import AuthProvider from "../../providers/AuthProvider"; // Ensure correct import path

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ecovision Partners",
  description: "Generated by create next app",
  icons: {
    icon: '/public/logo.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
        <head>
        <link rel="icon" href="/public/logo.png" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Wrap the entire application with AuthProvider */}
        <AuthProvider>
          <nav >
            <NavBar />
          </nav>

          <div className="min-h-screen">{children}</div>
    
          <footer>
            <Footer />
          </footer>
        </AuthProvider>
      </body>
    </html>
  );
}
